#index:
#    path: /
#    controller: App\Controller\DefaultController::index

criar_medico:
  path: /medico
  controller: App\Controller\MedicosController::novo
  methods:
    - POST

medicos:
  path: /medicos
  controller: App\Controller\MedicosController::buscarTodos
  methods:
    - GET

medico:
  path: /medico/{id}
  controller: App\Controller\MedicosController::buscarUm
  methods:
    - GET

atualiza_medico:
  path: /medico/{id}
  controller: App\Controller\MedicosController::atualiza
  methods:
    - PUT

remove_medico:
  path: /medico/{id}
  controller: App\Controller\MedicosController::remove
  methods:
    - DELETE

criar_especialidade:
  path: /especialidade
  controller: App\Controller\EspecialidadesController::novo
  methods:
    - POST

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::buscarTodos
  methods:
    - GET

especialidade:
  path: /especialidade/{id}
  controller: App\Controller\EspecialidadesController::buscarUm
  methods:
    - GET

atualiza_especialidade:
  path: /especialidade/{id}
  controller: App\Controller\EspecialidadesController::atualiza
  methods:
    - PUT

remove_especialidade:
  path: /especialidade/{id}
  controller: App\Controller\EspecialidadesController::remove
  methods:
    - DELETE